initial commit

diff --git a/hooks/install b/hooks/install
--- a/hooks/install
+++ b/hooks/install
@@ -1,34 +1,173 @@
 #!/bin/bash
 
-set -ex
+#set -ex
+#
+#RELEASE=$(lsb_release -r -s | awk -F. '{print $1}')
+#
+#if [ $RELEASE -lt 16 ]; then
+#    STOP_REQUIRED=True
+#fi
+#
+#debconf-set-selections <<EOF
+#slapd slapd/internal/adminpw password crapper
+#slapd slapd/password1 password crapper
+#slapd slapd/password2 password crapper
+#slapd slapd/domain string test.com
+#slapd shared/organization string test
+#EOF
+#
+#apt -y install slapd ldap-utils phpldapadmin
+#
+#sed -i "s/dc=example/dc=test/g" /etc/phpldapadmin/config.php
+#service apache2 restart
+#
+#if [ $STOP_REQUIRED ]; then
+#    service slapd stop
+#fi
+#
+#slapadd -v -c -l files/backup.ldif
+#
+#if [ $STOP_REQUIRED ]; then
+#    service slapd start
+#fi
+#
+#status-set 'active' 'Unit is ready'
 
-RELEASE=$(lsb_release -r -s | awk -F. '{print $1}')
 
-if [ $RELEASE -lt 16 ]; then
-    STOP_REQUIRED=True
-fi
+set -e
 
-debconf-set-selections <<EOF
-slapd slapd/internal/adminpw password crapper
-slapd slapd/password1 password crapper
-slapd slapd/password2 password crapper
-slapd slapd/domain string test.com
-slapd shared/organization string test
-EOF
 
-apt -y install slapd ldap-utils phpldapadmin
+hostnamectl set-hostname kerberos.testubuntu.com
+IP_ADDRESS=$(hostname -I | awk '{print $1}')
+export KERBEROS_HOSTNAME=$(cat /etc/hostname)
+export KERBEROS_USERNAME='admin'
+export KERBEROS_PASSWORD='password123'
+export KERBEROS_REALM='TESTUBUNTU.COM'
+export DEBIAN_FRONTEND=noninteractive
 
-sed -i "s/dc=example/dc=test/g" /etc/phpldapadmin/config.php
-service apache2 restart
 
-if [ $STOP_REQUIRED ]; then
-    service slapd stop
-fi
+sudo sed -i "/.*$HOSTNAME/c\\$IP_ADDRESS\t$KERBEROS_HOSTNAME" /etc/hosts
 
-slapadd -v -c -l files/backup.ldif
 
-if [ $STOP_REQUIRED ]; then
-    service slapd start
-fi
+echo "Setting up Kerberos config file at /etc/krb5.conf"
+cat > /etc/krb5.conf << EOL
+[libdefaults]
+    default_realm = ${KERBEROS_REALM^^}
+    dns_lookup_realm = false
+    dns_lookup_kdc = false
+[realms]
+    ${KERBEROS_REALM^^} = {
+        kdc = $KERBEROS_HOSTNAME
+        admin_server = $KERBEROS_HOSTNAME
+    }
+[domain_realm]
+    .$KERBEROS_REALM = ${KERBEROS_REALM^^}
+[logging]
+    kdc = FILE:/var/log/krb5kdc.log
+    admin_server = FILE:/var/log/kadmin.log
+    default = FILE:/var/log/krb5lib.log
+EOL
+
+echo "Setting up kerberos ACL configuration at /etc/krb5kdc/kadm5.acl"
+mkdir /etc/krb5kdc
+echo -e "*/*@${KERBEROS_REALM^^}\t*" > /etc/krb5kdc/kadm5.acl
+
+echo "Installing all the packages required in this test"
+apt-get update
+apt-get \
+    -y \
+    -qq \
+    install \
+    krb5-{user,kdc,admin-server,multidev} \
+    libkrb5-dev \
+    wget \
+    curl \
+    apache2 \
+    libapache2-mod-auth-gssapi \
+    python-dev \
+    libffi-dev \
+    build-essential \
+    libssl-dev \
+    zlib1g-dev \
+    libbz2-dev
+
+echo "Creating KDC database"
+# krb5_newrealm returns non-0 return code as it is running in a container, ignore it for this command only
+set +e
+printf "$KERBEROS_PASSWORD\n$KERBEROS_PASSWORD" | krb5_newrealm
+set -e
+
+echo "Creating principals for tests"
+kadmin.local -q "addprinc -pw $KERBEROS_PASSWORD $KERBEROS_USERNAME"
+
+echo "Adding HTTP principal for Kerberos and create keytab"
+kadmin.local -q "addprinc -randkey HTTP/$KERBEROS_HOSTNAME"
+kadmin.local -q "ktadd -k /etc/krb5.keytab HTTP/$KERBEROS_HOSTNAME"
+chmod 777 /etc/krb5.keytab
+
+echo "Restarting Kerberos KDS service"
+service krb5-kdc restart
+
+echo "Add ServerName to Apache config"
+grep -q -F "ServerName $KERBEROS_HOSTNAME" /etc/apache2/apache2.conf || echo "ServerName $KERBEROS_HOSTNAME" >> /etc/apache2/apache2.conf
+
+echo "Deleting default virtual host file"
+rm /etc/apache2/sites-enabled/000-default.conf
+rm /etc/apache2/sites-available/000-default.conf
+rm /etc/apache2/sites-available/default-ssl.conf
+
+echo "Create website directory structure and pages"
+mkdir -p /var/www/example.com/public_html
+chmod -R 755 /var/www
+echo "<html><head><title>Title</title></head><body>body mesage</body></html>" > /var/www/example.com/public_html/index.html
+
+echo "Create self signed certificate for HTTPS endpoint"
+mkdir /etc/apache2/ssl
+openssl req \
+    -x509 \
+    -nodes \
+    -days 365 \
+    -newkey rsa:2048 \
+    -keyout /etc/apache2/ssl/https.key \
+    -out /etc/apache2/ssl/https.crt \
+    -subj "/CN=$KERBEROS_HOSTNAME/o=Testing LTS./C=US"
+
+echo "Create virtual host files"
+cat > /etc/apache2/sites-available/example.com.conf << EOL
+<VirtualHost *:80>
+    ServerName $KERBEROS_HOSTNAME
+    ServerAlias $KERBEROS_HOSTNAME
+    DocumentRoot /var/www/example.com/public_html
+    ErrorLog ${APACHE_LOG_DIR}/error.log
+    CustomLog ${APACHE_LOG_DIR}/access.log combined
+    <Directory "/var/www/example.com/public_html">
+        AuthType GSSAPI
+        AuthName "GSSAPI Single Sign On Login"
+        Require user $KERBEROS_USERNAME@${KERBEROS_REALM^^}
+        GssapiCredStore keytab:/etc/krb5.keytab
+    </Directory>
+</VirtualHost>
+<VirtualHost *:443>
+    ServerName $KERBEROS_HOSTNAME
+    ServerAlias $KERBEROS_HOSTNAME
+    DocumentRoot /var/www/example.com/public_html
+    ErrorLog ${APACHE_LOG_DIR}/error.log
+    CustomLog ${APACHE_LOG_DIR}/access.log combined
+    SSLEngine on
+    SSLCertificateFile /etc/apache2/ssl/https.crt
+    SSLCertificateKeyFile /etc/apache2/ssl/https.key
+    <Directory "/var/www/example.com/public_html">
+        AuthType GSSAPI
+        AuthName "GSSAPI Single Sign On Login"
+        Require user $KERBEROS_USERNAME@${KERBEROS_REALM^^}
+        GssapiCredStore keytab:/etc/krb5.keytab
+    </Directory>
+</VirtualHost>
+EOL
+
+echo "Enabling virtual host site"
+a2enmod ssl
+a2ensite example.com.conf
+systemctl restart apache2
 
 status-set 'active' 'Unit is ready'
